# Generated by Django 3.1.7 on 2021-02-25 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('datid', models.AutoField(primary_key=True, serialize=False)),
                ('datnombre', models.CharField(max_length=50)),
                ('datapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('datipoid', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('TI', 'Tarjeta de Identidad (TI)'), ('RC', 'Registro Civil (RC)'), ('CE', 'Cédula de Extranjería (CE)'), ('CI', 'Carné de Identidad (CI)'), ('DNI', 'Documento Nacional de Identidad (DNI)'), ('DUI', 'Documento Único de Identidad (DUI)')], default='CC', max_length=20, null=True)),
                ('datnumeroid', models.CharField(blank=True, max_length=20, null=True)),
                ('datelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('datcorreo', models.CharField(blank=True, max_length=50, null=True)),
                ('foto', models.ImageField(default='usuarios/usuario.png', upload_to='usuarios')),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Persona',
                'verbose_name_plural': 'Datos Personales',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('roltipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehplaca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehmodelo', models.IntegerField()),
                ('vehmarca', models.CharField(max_length=50)),
                ('vehestado', models.CharField(blank=True, max_length=30, null=True)),
                ('vehprecio', models.IntegerField()),
                ('vehfoto', models.ImageField(default='vehiculos/vehiculo.png', upload_to='vehiculos')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.categoria')),
                ('datid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.datospersonales')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.rol')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol Usuario',
                'verbose_name_plural': 'Roles Usuarios',
            },
        ),
    ]
